project:
  name: @project.artifactId@
  version: @project.version@

logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

spring:
  security:
    user:
      name: admin
      password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    hibernate.ddl-auto: update
java:
  security:
    Security.setProperty: "securerandom.source=file:/dev/urandom"
management:
  endpoints:
    web:
      exposure:
        include: '*'

